name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install Dependency
      run: go mod download github.com/cavaliercoder/grab && go get monun/server-script/utils/logger
    
    - name: Build macOS
      run: mkdir -p build && GOOS=darwin GOARCH=amd64 go build -o build/server_macOS
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: macOS
        path: ./build/server_macOS
        
    - name: Build Linux x64
      run: GOOS=linux GOARCH=amd64 go build -o build/server_linux_x64
    - name: Upload Linux x64 Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Linux x64
        path: ./build/server_linux_x64
        
    - name: Build Linux x86
      run: GOOS=linux GOARCH=386 go build -o build/server_linux_x86
    - name: Upload Linux x86 Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Linux x86
        path: ./build/server_linux_x86
        
    - name: Build Windows x64
      run: GOOS=windows GOARCH=amd64 go build -o build/server_windows_x64.exe
    - name: Upload Windows x64 Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Windows x64
        path: ./build/server_windows_x64.exe
        
    - name: Build Windows x86
      run: GOOS=windows GOARCH=386 go build -o build/server_windows_x86.exe
    - name: Upload Windows x86 Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Windows x86
        path: ./build/server_windows_x86.exe
        
    - name: Release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: "./build/*"
        body: Auto Build Triggered by a commit
        name: Auto Release
        tag: Actions
        Prerelease: false
        token: ${{ secrets.TOKEN }}
